module.exports =  [
        "Afghanistan",
        "Akrotiri and Dhekelia (UK)",
        "Aland Islands (Finland)",
        "Albania",
        "Algeria",
        "American Samoa (USA)",
        "Andorra",
        "Angola",
        "Anguilla (UK)",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba (Netherlands)",
        "Ascension Island (UK)",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda (UK)",
        "Bhutan",
        "Bolivia",
        "Bonaire (Netherlands)",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "British Indian Ocean Territory (UK)",
        "British Virgin Islands (UK)",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Caribbean Netherlands (Netherlands)",
        "Cayman Islands (UK)",
        "Central African Republic",
        "Chad",
        "Chatham Islands (New Zealand)",
        "Chile",
        "China",
        "Christmas Island (Australia)",
        "Cocos (Keeling) Islands (Australia)",
        "Colombia",
        "Comoros",
        "Congo, Democratic Republic of the",
        "Congo, Republic of the",
        "Cook Islands (New Zealand)",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatia",
        "Cuba",
        "Curacao (Netherlands)",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (UK)",
        "Faroe Islands (Denmark)",
        "Fiji",
        "Finland",
        "France",
        "French Guiana (France)",
        "French Polynesia (France)",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar (UK)",
        "Greece",
        "Greenland (Denmark)",
        "Grenada",
        "Guadeloupe (France)",
        "Guam (USA)",
        "Guatemala",
        "Guernsey (UK)",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hong Kong (China)",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "International Monetary Fund (IMF)",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle of Man (UK)",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey (UK)",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macau (China)",
        "Macedonia (FYROM)",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique (France)",
        "Mauritania",
        "Mauritius",
        "Mayotte (France)",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat (UK)",
        "Morocco",
        "Mozambique",
        "Myanmar (Burma)",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Caledonia (France)",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue (New Zealand)",
        "Norfolk Island (Australia)",
        "Northern Mariana Islands (USA)",
        "North Korea",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn Islands (UK)",
        "Poland",
        "Portugal",
        "Puerto Rico (USA)",
        "Qatar",
        "Reunion (France)",
        "Romania",
        "Russia",
        "Rwanda",
        "Saba (Netherlands)",
        "Saint Barthelemy (France)",
        "Saint Helena (UK)",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (France)",
        "Saint Pierre and Miquelon (France)",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Sint Eustatius (Netherlands)",
        "Sint Maarten (Netherlands)",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia Island (UK)",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen (Norway)",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau (New Zealand)",
        "Tonga",
        "Trinidad and Tobago",
        "Tristan da Cunha (UK)",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands (UK)",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States of America",
        "Uruguay",
        "US Virgin Islands (USA)",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City (Holy See)",
        "Venezuela",
        "Viet Nam",
        "Wake Island (USA)",
        "Wallis and Futuna (France)",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ]